// <auto-generated />
using System;
using ControlInformes.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlInformes.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429053105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlInformes.Domain.Entities.Asistencia", b =>
                {
                    b.Property<Guid>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoReunion")
                        .HasColumnType("int");

                    b.HasKey("IdAsistencia");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capitan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGrupo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.InformeMensual", b =>
                {
                    b.Property<Guid>("IdInformeMensual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("CursosBiblicos")
                        .HasColumnType("int");

                    b.Property<int?>("Horas")
                        .HasColumnType("int");

                    b.Property<Guid>("IdPublicador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<bool>("Participo")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdInformeMensual");

                    b.HasIndex("IdPublicador", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("InformesMensuales");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Publicador", b =>
                {
                    b.Property<Guid>("IdPublicador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBautismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdPublicador");

                    b.ToTable("Publicadores");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.PublicadorGrupo", b =>
                {
                    b.Property<Guid>("IdPublicadorGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGrupo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPublicador")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPublicadorGrupo");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdPublicador");

                    b.ToTable("PublicadorGrupos");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.InformeMensual", b =>
                {
                    b.HasOne("ControlInformes.Domain.Entities.Publicador", "Publicador")
                        .WithMany("InformesMensuales")
                        .HasForeignKey("IdPublicador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicador");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.PublicadorGrupo", b =>
                {
                    b.HasOne("ControlInformes.Domain.Entities.Grupo", "Grupo")
                        .WithMany("PublicadorGrupos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlInformes.Domain.Entities.Publicador", "Publicador")
                        .WithMany("PublicadorGrupos")
                        .HasForeignKey("IdPublicador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Publicador");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("PublicadorGrupos");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Publicador", b =>
                {
                    b.Navigation("InformesMensuales");

                    b.Navigation("PublicadorGrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
