// <auto-generated />
using System;
using ControlInformes.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlInformes.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlInformes.Domain.Entities.Asistencia", b =>
                {
                    b.Property<Guid>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadPresencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CantidadVirtual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("FechaReunion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TipoReunion")
                        .HasColumnType("int");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("FechaReunion", "TipoReunion")
                        .IsUnique()
                        .HasFilter("[TipoReunion] IS NOT NULL");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCapitan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGrupo");

                    b.HasIndex("IdCapitan");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.InformeMensual", b =>
                {
                    b.Property<Guid>("IdInformeMensual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("CursosBiblicos")
                        .HasColumnType("int");

                    b.Property<int?>("Horas")
                        .HasColumnType("int");

                    b.Property<Guid>("IdPublicador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Inactivo")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Participo")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdInformeMensual");

                    b.HasIndex("IdPublicador", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("InformesMensuales");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Publicador", b =>
                {
                    b.Property<Guid>("IdPublicador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CondicionEspiritual")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBautismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdGrupo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Inactivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdPublicador");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Publicadores");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("ControlInformes.Domain.Entities.Publicador", "Capitan")
                        .WithMany()
                        .HasForeignKey("IdCapitan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capitan");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.InformeMensual", b =>
                {
                    b.HasOne("ControlInformes.Domain.Entities.Publicador", "Publicador")
                        .WithMany("InformesMensuales")
                        .HasForeignKey("IdPublicador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicador");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Publicador", b =>
                {
                    b.HasOne("ControlInformes.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Publicadores")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Publicadores");
                });

            modelBuilder.Entity("ControlInformes.Domain.Entities.Publicador", b =>
                {
                    b.Navigation("InformesMensuales");
                });
#pragma warning restore 612, 618
        }
    }
}
