<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ControlInformes.Domain\ControlInformes.Domain.csproj" />
    <ProjectReference Include="..\ControlInformes.Data\ControlInformes.Data.csproj" />
    <ProjectReference Include="..\ControlInformes.Utils\ControlInformes.Utils.csproj" />
  </ItemGroup>

</Project>
